spring.datasource.url=jdbc:postgresql://ep-quiet-haze-a5m5j99y-pooler.us-east-2.aws.neon.tech/softdevdb?sslmode=require
spring.datasource.username=softdevdb_owner
spring.datasource.password=npg_7hymNUHTWl1d
